package com.yagmur.utility.enums;

public enum EBrans {
    ACIL_TIP,
    BEYIN_SINIR_CERRAHISI,
    COCUK_HASTALIKLARI,
    DAHILIYE,
    GENEL_CERRAHI,
    GOZ_HASTALIKLARI,
    KADIN_HASTALIKLARI_VE_DOGUM,
    KULAK_BURUN_BOGAZ,
    ORTOPEDI,
    PSIKIYATRI,
    DERMATOLOJI,
    FIZYOTERAPI,
    UROLOJI,
    GASTROENTEROLOJI,
    ONKOLOJI,
    GOGUS_HASTALIKLARI,
    NOROLOJI;


}
